import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "../components/Header";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <header className="fixed top-0 left-0 right-0 z-50 bg-white">
          <div className="py-2">
            <Header />
          </div>
        </header>
        <main
          className="flex-1 container mx-auto px-4 py-6"
          style={{ marginTop: "var(--header-height, 5rem)" }}
        >
          {children}
        </main>

        {/* <footer className="mt-auto">
          <div className="py-6">
            <Footer />
          </div>
        </footer> */}
      </body>
    </html>
  );
}
